### ISSUE TITLE
Unable to redirect URLs that have a URL pattern in the `routes.php` file

### ISSUE THREAD

**Issue by trangiiee** [nystudio107/retour#100]
Hello! 

You're plugin is great! We love it, but we are having one issue: 

Our `routes.php` file has a URL pattern like below:

``` php 
return array(
  'find-providers/provider/[^\/]+' => 'find-providers/_entry',
);
```

And we have an entry like below: 
![screen shot 2018-05-03 at 1 57 47 pm](https://user-images.githubusercontent.com/1852539/39594210-ff58435c-4ed9-11e8-9688-9f29cb49fb38.png)

If we try to go to http://example.com/find-providers/provider/nichole-hickman-np-6714, it will not redirect to http://example.com/find-providers/provider/nichole-e-hickman-np-6714

We believe that the `routes.php` file is trumping the redirects from this plugin.

Any help with this would be appreciated.

Thank you!

**Comment by darinlarimore** [comment]
Hey there, we ended up fixing this by forcing the template to 404 which allowed the redirects to work just as they should!

```
{% if data | length == ""  %}
  {% exit 404 %}
{% endif %}
```

We added this to the template.

**Comment by benjamin-smith** [comment]
For anyone stumbling on this after a _long_ time, this was added in version 1.0.18

https://github.com/nystudio107/retour/blob/658cdea255a2b6726a77c887b7294ab75be244c2/releases.json#L59

**Comment by khalwat** [comment]
@benjamin-smith this is the old Craft 2 repo -- now deprecated

**Comment by benjamin-smith** [comment]
Boy don't I wish the site I was working on was on Craft 4 :) I spent a couple extra cycles debugging this until I saw the plugin was a couple versions back. Just leaving the note for posterity.
