### ISSUE TITLE
Create a way to programmatically add redirects to Retour from other plugins

### ISSUE THREAD

**Issue by trangiiieee** [nystudio107/retour#101]
Hi there!

Is there a way to programmatically add redirects to Retour? 

So in another plugin, we can call something like: 

``` php 
craft()->retour->addRedirect( $legacyUrlPattern, $destinationUrl, $patternMatchType, $redirectType );
```

Thanks!

**Comment by khalwat** [comment]
Yep, see here: https://github.com/nystudio107/retour#developer-info
