### ISSUE TITLE
Copying resources to /cpresources/retour/

### ISSUE THREAD

**Issue by jdsdev** [nystudio107/retour#106]
Every time I push a new build I clear the web directory. Craft automatically re-generates the /cpresources directory again. Retour doesn't re-copy resources to /cpresources/retour, but it continues to look for resources there.

**Comment by jwmatlock** [comment]
This is happening to us as well.

**Comment by khalwat** [comment]
I believe this is for the Craft 3 version, which is here: https://github.com/nystudio107/craft-retour
