### ISSUE TITLE
craft.retour.getHttpStatus gives 200 after 301 redirect 

### ISSUE THREAD

**Issue by gbowne-quickbase** [nystudio107/retour#117]
### Question
We set up a 301 redirect from `/blog/(.*)` to `/blog` to handle a bunch of content we're deleting and want to send them to our blog's home page, but let them know that they probably were looking for something that's gone now.

We found the cool feature `craft.retour.getHttpStatus` that should give us a 301/302 based on how the visitor arrived at that page, but we seem to only get a 200, regardless of how the redirect is set up. 

### Additional context
Here's the line from the retour redirects screen:
![image](https://user-images.githubusercontent.com/39066452/141521279-75c2c421-4425-41b5-97fd-24e7c092ddd6.png)

Here's the code we're running to get that status and act on it:
![image](https://user-images.githubusercontent.com/39066452/141521361-139f34af-534b-4324-aebc-d57cea151ddd.png)

Here's what we see on the page, sadly, just the `200`
![image](https://user-images.githubusercontent.com/39066452/141521456-79bca1e4-8045-47f2-8acb-f249a60f13f3.png)

Looking at the network tab, we are getting a `301` that throws us to the right page, but that gives us a `200`:
![image](https://user-images.githubusercontent.com/39066452/141522058-b1313afe-1957-4070-aab2-d470b0a2e979.png)

**Comment by khalwat** [comment]
So unfortunately, I think that `getHttpStatus` might be a little misleading. It tells you the status for the _current_ request, and was just added in there as a convenience because there weren't any other great ways to get it.

So the `200` you're getting is right... it just pertains to the _current_ request.
