### ISSUE TITLE
Csv import seems to skip the first one

### ISSUE THREAD

**Issue by bob-pixeldeluxe** [nystudio107/retour#121]
### To reproduce
Steps to reproduce the behaviour:
1. Go to make an csv file to import 301 redirect.
2. Import the file this shows the following 
<img width="2078" alt="Screenshot 2024-04-02 at 15 26 20" src="https://github.com/nystudio107/retour/assets/50947605/bb346cc7-d2a4-44d4-9ff4-fa28ef1c742f">
3. Now after the import if I search all seems te be added except for the first one "test in the screenshot above".
<img width="2076" alt="Screenshot 2024-04-02 at 15 27 04" src="https://github.com/nystudio107/retour/assets/50947605/d472da21-7c23-4aaf-b04c-5a21ee335f42">
4. If i put something else as the first one this one is skipped as well.

### Versions
- Plugin version: 4.1.15
- Craft version: 4.7.2.1

**Comment by khalwat** [comment]
The first entry in the CSV should be the columns, which have the names of the columns in there. So it's not skipping it, it's using that first row as the column titles.
