### ISSUE TITLE
Switching Blitz to Cloudfront has broken Retour it seems

### ISSUE THREAD

**Issue by jan-dh** [nystudio107/retour#122]
### Describe the bug
Since switching to Cloudfront in combination with Blitz static file caching it seems retour is broken. I get 
- "no data available" for both the dashboard and the redirects
- clicking the "export CSV" redirects me to the homepage of the website (outside the admin panel)

### Screenshots
<img width="536" alt="image" src="https://github.com/nystudio107/retour/assets/5801781/04cbe620-67d7-431e-aaab-57995a9a4336">

### Versions
- Plugin version: 4.1.16
- Craft version: 4.8.9

**Comment by jan-dh** [comment]
Hmm, seems this has everything to do with urls of these types: `index.php?p=admin/actions/retour/charts/dashboard` that needed to be added to the cache whitelisting.

**Comment by khalwat** [comment]
Glad you sorted it out

I'm not sure the CP is a good thing to run through CloudFront generally speaking, though?

**Comment by jan-dh** [comment]
Yep, that was the issue, I only had the `/admin` whitelisted, not the `index?p=admin`
