### ISSUE TITLE
Add support for domaine redirect

### ISSUE THREAD

**Issue by Megafry** [nystudio107/retour#123]
### Is your feature request related to a problem? Please describe.
My customer has a lot of domains he bought for redirects.

I could not find a way to redirect just a domain, I also tried to use regex:
```
https://exemple-internet.ch(.*)
# no redirect https://exemple-internet.ch
# redirect https://exemple-internet.ch/old 
```
The goal:
```
exemple-internet.ch -> exemple.ch/abos/internet
exemple-internet.ch/old-> exemple.ch/abos/internet
exemple-energie.ch -> exemple.ch/energie
```
### Describe the solution you would like

**Approach 1:**
Make the regex `https://exemple-internet.ch(.*)` also match for `https://exemple-internet.ch`

**Approach 2:**
Add a checkbox to allow match any.

**Approach 3:**
Add an option "Custom" to the field Sites.
If selected, a new field becomes visible to set the URL. (ex: exemple-internet.ch)

![image](https://github.com/user-attachments/assets/5b8135f9-e335-4bd7-a12e-72858fde7368)

### Describe alternatives you have considered
I try regex but without success.

**Comment by khalwat** [comment]
The issue here is you're using "Path Only" which ignores the domain part of the URL. Switch it to **Full URL**

https://nystudio107.com/docs/retour/configuring.html#manually-creating-static-redirects

> Legacy URL Pattern - Enter the URL pattern that Retour should match. This matches against the path only (the part of the URL after the domain name), or the full URL, depending on the setting of Legacy URL Match Type. For example: Exact Match: /recipes/ or http://example.com/recipes/, or regular expression Match: .*RecipeID=(.*)

**Comment by Megafry** [comment]
@khalwat You are right it works with full URL, but unfortunately, I could not find a way to redirect a URL widout path.

The goal is to redirect `https://exemple-internet.ch` to `https://exemple.ch/abo/internet` 

The redirect only works if the URL has a path
- https://exemple-internet.ch -> The redirection does not work:
- https://exemple-internet.ch/campaign-xyz -> https://exemple.ch/abo/internet


My config:
![image](https://github.com/user-attachments/assets/7482e9e7-4419-4c10-96e7-9c650f365d24)

**Comment by khalwat** [comment]
Maybe try:

```
https://exemple-internet.ch(.*)
```

?

**Comment by Megafry** [comment]
I tried all possible options the tool provides.
Unfortunately, this also doesn't work.
```
https://exemple-internet.ch(.*)
```
