### ISSUE TITLE
Retour statistics crashes page

### ISSUE THREAD

**Issue by admench** [nystudio107/retour#13]
Hi Andrew,

I have an issue when clicking on retour statistics - the page doesn't refresh, it simply hangs trying to process the request, then eventually after 30 seconds or so it displays a 500 error page.

What logs should I check to give you more info?

Thanks for a great plugin.
Adam

**Comment by admench** [comment]
using:	
Retour 1.0.9

**Comment by admench** [comment]
Craft CMS 2.6.2791

**Comment by khalwat** [comment]
So the code is actually pretty simple, so my only guess is you have a TON of statistics, and it's timing out trying to fetch & render them all.

Try the build I just checked into `develop`:

https://github.com/nystudio107/retour/tree/develop

...which limits the results to 1,000

**Comment by khalwat** [comment]
Any updates on this?

**Comment by admench** [comment]
Hey,

The 1000 limit has fixed this. The page loads nice and quickly now too!

Thank you very much!
Have a good day!
