### ISSUE TITLE
Can this handle old urls from .net site?

### ISSUE THREAD

**Issue by subratom** [nystudio107/retour#15]
I have a lot of data that is being imported into CraftCMS. I don't want to write rules to redirect 80K items from old CMS to new CMS and I am trying not to change the domain URL. I want to use this plugin but not sure if I can use 
www.example.com/<category>/<subcategory>/title_name.aspx
www.example.com/<category>/title_name.aspx

P.S. I am learning how to use the CMS so let me know if this is a stupid question

**Comment by khalwat** [comment]
Yes, Retour can definitely do this for you.  Check out the docs on the FieldType.
