### ISSUE TITLE
URL for 410 errors

### ISSUE THREAD

**Issue by kaspar-allenbach** [nystudio107/retour#16]
Referring to this [ticket](https://github.com/nystudio107/retour/issues/10)

As far as I understand the redirect field doesn't work when using the 410 error code.

I have a lot of invalid image assets so I thought about creating an image which states "this resource is no longer available" and adding this image as a redirect path.

Would this be possible?

**Comment by kaspar-allenbach** [comment]
I found a (cheap) solution. I use a 301 redirect to redirect to a site with a http 410 status code. Not the prettiest thing. but it works.

**Comment by khalwat** [comment]
I'm confused.  I did add support for returning the 410 error code.  Is it not working for you?

**Comment by khalwat** [comment]
??

**Comment by kaspar-allenbach** [comment]
Hi. I made some strange toughts there. Nevermind. The 410 function is working as expected.
