### ISSUE TITLE
BUG: Duplicating page causes automatic rewrite

### ISSUE THREAD

**Issue by fyrebase** [nystudio107/retour#17]
When duplicating a page Craft also duplicates the slug and upon updating the slug Retour creates an automatic rewrite for the updated slug

**Comment by khalwat** [comment]
huh.  Weird, if I look at the slug `onBeforeSave` it's already changed, so I can't key off of that.

And strangely, when you duplicate an entry, it doesn't set `isNewEntry`, which you'd think it would.

**Comment by khalwat** [comment]
So here's what I did to test it:

I went to an entry, and clicked on "Save as new entry" -- this saved a new entry with a new slug, and didn't create  redirect.

Can you give me the steps to reproduce please?
