### ISSUE TITLE
Create setting to allow use of {siteUrl} in redirect destination

### ISSUE THREAD

**Issue by fyrebase** [nystudio107/retour#18]
Currently the site domain is stored in the redirect destination and causes problems when pushing to different environments

**Comment by khalwat** [comment]
The site domain should not be saved in the redirect, it should be just the URI.  How are you getting the domain to be in there?

**Comment by khalwat** [comment]
Fixed in 1.1.12, which is checked into `develop`:

https://github.com/nystudio107/retour/tree/develop

[Improved] We now store the destination for redirects in the FieldType as a URI rather than a URL, so that it's more portable across environments
