### ISSUE TITLE
Enhancement: Static Redirects: Throw error if legacy URL pattern is set but no redirect provided

### ISSUE THREAD

**Issue by fyrebase** [nystudio107/retour#19]
When creating a static redirect if a user provides a legacy URL pattern but no redirect and error should potentially be raised

**Comment by khalwat** [comment]
Probably will leave this as-is, in case people want to redirect to the home page (which leaving it blank should be a shortcut to doing)

**Comment by fyrebase** [comment]
Leaving it blank for me redirects to a blank screen. I had to add a `/` to redirect to the home page

**Comment by khalwat** [comment]
[Improved] Retour will no longer let you save a static redirect with an empty destinationURL

Change checked into `develop`:

https://github.com/nystudio107/retour/tree/develop
