### ISSUE TITLE
FR: Statistics dashboard widget

### ISSUE THREAD

**Issue by johanneslamers** [nystudio107/retour#2]
Would be nice to have a dashboard widget to show latest 404 errors.

**Comment by khalwat** [comment]
That's a good idea :)

**Comment by johanneslamers** [comment]
:-)

**Comment by johanneslamers** [comment]
And maybe a count number also.

**Comment by khalwat** [comment]
Count number of...?

**Comment by khalwat** [comment]
Widget is implemented in 1.0.3:

https://github.com/nystudio107/retour
