### ISSUE TITLE
BUG: Re-ordering a entry within a structure does not update redirect when using retour fieldtype

### ISSUE THREAD

**Issue by fyrebase** [nystudio107/retour#20]
When re-ordering a entry within a structure the redirect set in the retour fieldtype is not updated until you go into the entry and save or re-save the section

**Comment by khalwat** [comment]
Added a fix to `develop`:

https://github.com/nystudio107/retour/tree/develop

[Added] Structure entries that have Retour FieldTypes in them now have the destinationURL updated when the structure elements are moved
