### ISSUE TITLE
FR: Searchable and filterable Stats list and Redirects list

### ISSUE THREAD

**Issue by superwick** [nystudio107/retour#22]
Would love a way to filter the Statistics list by Handled/Unhandled, as well as filter via search box. Would also love the search box on the Redirects page.

**Comment by khalwat** [comment]
You can click on the Handled column (or any column) and it'll sort by it.

As for searching, I probably won't implement that, but you can just do Command-F or Control-F to search the page in any browser.

**Comment by superwick** [comment]
I know I can search in-browser and click on the column headings to sort... 

But, when you have hundreds of redirects in place and thousands of things listed in Statistics, it would be nice to use a live-search box and a filter dropdown (like on Entry lists in core Craft) to finds things really easily and only display what you want at a given time.  I have 1000 things listed in my Statistics page. What if I only wanted to see unhandled 404s that have the substring "product" in the url?

I'm willing to help on this. Accepting PRs?

**Comment by khalwat** [comment]
Yeah actually when I was first going to implement it, I was going to use DataTables to display the tables.  Maybe I still should.

**Comment by khalwat** [comment]
In case the above wasn't clear enough, I intend to implement it.

**Comment by khalwat** [comment]
[Added] The Statistics and Redirects tables are now dynamically searchable and sortable

It's checked into `develop` if you want to give it a whirl:

https://github.com/nystudio107/retour/tree/develop
