### ISSUE TITLE
404 Page error

### ISSUE THREAD

**Issue by KoenRijpstra** [nystudio107/retour#23]
I updated to latest version and the 404 page gives the following error:
```
CException

The attribuut "Craft\Retour_StatsRecord.referrerUrl" is not defined.
```

**Comment by khalwat** [comment]
I'm guessing that somehow the migration didn't run.  You can try manually running it via:

https://craftcms.com/docs/plugins/migrations#yiic-migrate-up-pluginHandle

Or you can uninstall and reinstall the plugin (yes, that will cause data loss, however).
