### ISSUE TITLE
'Quick Add' from statistics page not working

### ISSUE THREAD

**Issue by michaelroper** [nystudio107/retour#24]
The recently-added feature of being able to add a redirect straight from a 404 off the statistics list doesn't seem to work for me - it just reloads the same page with the destination url field empty again. (If i add it via the new static redirect process instead, it works.) (also, using v1.0.13)

**Comment by khalwat** [comment]
Can you hover over one of the + signs, and right-click to copy the URL, and paste it in here?

**Comment by khalwat** [comment]
This is fixed in 1.0.14:

https://github.com/nystudio107/retour
