### ISSUE TITLE
changing an entry link from /url-1 to /url-2 to /url-1 shows both redirects in the redirects list

### ISSUE THREAD

**Issue by lexbi** [nystudio107/retour#26]
Hi khal, 
Just trying your Retour plugin for the first time, so far appears to work great so thanks for your efforts in to making it!
Just wanted to ask if there’s anything in there to deal with where a situation where the page is on `/url-1`, changes to `/url-2`, then back to `/url-1`, it appears at the moment that no redirect loop is happening and technically works absolutely fine, but I can see both the redirects in the dashboard still on the list at `/admin/retour/redirects`

**Comment by khalwat** [comment]
I'm on vacation atm, but I'll have a look when I get back (or when I get a chance).  If anyone else can test this, that'd be helpful as well.

It should be deleting the redirect that would cause a redirect loop, there is logic in there to do it, but then it shouldn't be listed in the list of redirects.

**Comment by khalwat** [comment]
I *think* this might be fixed by the build checked into `develop`:

https://github.com/nystudio107/retour/tree/develop

**Comment by khalwat** [comment]
So I'm a bit flummoxed by this; are you still having an issue with it?  Here's where it should be deleting the old redirect:

https://github.com/nystudio107/retour/blob/master/services/RetourService.php#L265
