### ISSUE TITLE
Test rules by host (or perhaps other conditions besides path)

### ISSUE THREAD

**Issue by timkelty** [nystudio107/retour#27]
e.g. here's the rule I'm making in .htaccess:

```
  RewriteCond %{HTTP_HOST} ^blog\.oldsite\.com [NC]
  RewriteRule \d+/\d+/(.+) http://www.newsite.com/blog/$1 [R=301,L]
```

**Comment by khalwat** [comment]
I'd suggest just having a general redirect from the old site to the new site (rewrite all accesses to the old domain to the corresponding page on the new domain), and then create your redirects in Retour as needed for old URL schemas.

Basically, break down what you're doing in one step into two:

1. Redirect old domain to new domain
2. Redirect deprecated URL patterns to the new patterns (if any)

You're going to have to do the old domain -> new domain redirect anyway.

**Comment by timkelty** [comment]
Yeah thats true.
In this case the matches can be different based on the incoming host, though.

In that case maybe I'll just redirect everything to prefix a slug so I can test on that.
