### ISSUE TITLE
Locale issues with fieldtype

### ISSUE THREAD

**Issue by timkelty** [nystudio107/retour#28]
## Problem 1:
- Marking a field as "translatable" doesn't seem to change behavior.

The field data should persist across all locales if it is _not_ translatable, but it doesn't.
## Problem 2:

_Retour Redirect fields don't seem to care what locale the field is entered in, nor what locale the request comes from *_

Example:
- `site.com` sets locale to `us`
- `site.co.uk` sets locale to `uk`
- Entry has no redirect in `us`
- Entry has redirect `/oldurl/` in `uk`

Expected behavour:
- `site.com/oldurl` should do nothing (404)
- `site.co.uk/oldurl` should redirect to `site.co.uk/newurl`

Actual:
- both `site.com/oldurl` and `site.co.uk/oldurl` redirect to `/newurl`
## Problem 3:

_Duplicate patterns don't save without any validation errors_
- enter `foobar` pattern in entry1
- enter `foobar` pattern in entry2

Entry is saved with no validation errors, but entry2 will not have saved the redirect data. The silent failing is a problem, as is the underlying requirement that they be unique, as patterns could be the same across different locales but potentially routing to different uris.

Example (both destinations are same entry, with different locale slugs):
- `site.com/oldurl` → `site.com/newurl`
- `site.co.uk/oldurl` → `site.co.uk/newurl-with-british-slug`

**Comment by khalwat** [comment]
## Problem 1:

`[Fixed] FieldTypes in multi-locale setups that are not translatable are now handled properly` checked into `develop`:

https://github.com/nystudio107/retour/tree/develop

**Comment by dommmel** [comment]
Another thing that used to work and now doesn't is locale prefix (e.g. /de/ ).
I have a site with two languages (en and de) and every second prefixed with /de/. Those prefixes don't get added when following a redirect.

**Comment by dommmel** [comment]
To fix this I replaced 

    $urlParts = parse_url($this->element->uri);

with 

    $urlParts = parse_url($this->element->url);

in 

https://github.com/nystudio107/retour/blob/master/fieldtypes/RetourFieldType.php#L135

**Comment by khalwat** [comment]
Merged it, thanks @dommmel -- I still have the issues to sort out that @timkelty mentioned tho, they aren't exactly related.
