### ISSUE TITLE
Error setting up on a Craft 2.4 website

### ISSUE THREAD

**Issue by swixpop** [nystudio107/retour#3]
I'm getting an error `Variable "continueEditingUrl" does not exist` when trying to access the settings page after installing on a Craft 2.4.2684 website.

It's coming from `/retour/templates/settings.twig(39)` where you call `{{ continueEditingUrl }}`. However, from what I can see `continueEditingUrl` isn't defined anywhere.

Thanks in advance

**Comment by khalwat** [comment]
Pushed a fix for you: https://github.com/nystudio107/retour

**Comment by khalwat** [comment]
This is fixed in 1.0.5
