### ISSUE TITLE
Exact match pattern match not working with Retour field

### ISSUE THREAD

**Issue by brettburwell** [nystudio107/retour#31]
The exact pattern match doesn't appear to be working with the Retour Fields I'm setting up. I've added the field to the section and gone into `Settings > Sections > [section]` and clicked save. I've also manually saved a few entries just to be safe. 

I've successfully tested a static redirect, so I know at a base level the plugin is working.

Here's a screen shot of the corresponding retour field config (I've imported the entries using Feed Me, so the slugs should definitely trigger match):
![retour-field](https://cloud.githubusercontent.com/assets/1228671/17450800/0c52005e-5b28-11e6-8267-f9d9162419ee.jpg)

Here's the field in one of the tested entries.
![retour-field-entry](https://cloud.githubusercontent.com/assets/1228671/17450812/1c346840-5b28-11e6-99a0-3d2e4a35ffc6.jpg)

Here's a grab of the Retour Redirects page.
![retour-redirects](https://cloud.githubusercontent.com/assets/1228671/17450869/686128de-5b28-11e6-8d28-84e566584430.jpg)

And here's the Statistics page.
![retour-stats](https://cloud.githubusercontent.com/assets/1228671/17450875/6f492fb6-5b28-11e6-912e-0184c74d3e34.jpg)

The site is running Craft 2.6.2798 and Retour 1.0.15. 

I'm guessing this is a user error on my part, but I'm not quite sure what I might be missing. Any insight would be much appreciated.

**Comment by c0py** [comment]
I am getting exactly the same issue, only one dynamic entry is created (always the first element created in that section). I was expecting all elements to have a dynamic redirect.

I have tested this on two sections, one which had Feedme imported entries, and another which had manually created entries and the behavior is exactly the same.

**Comment by khalwat** [comment]
I checked in a fix to `develop`: 

https://github.com/nystudio107/retour/tree/develop

Sorry this took so long!

**Comment by brettburwell** [comment]
Thanks for the followup on this @khalwat. Much appreciated.

**Comment by brettburwell** [comment]
Just did a quick test and can confirm that things are working as expected. Thanks again.
