### ISSUE TITLE
Urls with slashes on the end are having the final slash stripped when added from stats

### ISSUE THREAD

**Issue by bossanova808** [nystudio107/retour#32]
When I click the blue +button on stats, it takes an unhandled re-direct like

`/categories/Inkjet-Papers-By-Brand/Hahnemuhle-Papers/?p=categories/Inkjet-Papers-By-Brand/Hahnemuhle-Papers/`

and in the nee redirect page the legacy url pattern becomes
`/categories/Inkjet-Papers-By-Brand/Hahnemuhle-Papers/?p=categories/Inkjet-Papers-By-Brand/Hahnemuhle-Papers` - notice the lack of trailing slash.

So the created re-direct then does not work for the full url

Thanks!

**Comment by khalwat** [comment]
I checked a fix into the `develop` branch:

https://github.com/nystudio107/retour/tree/develop
