### ISSUE TITLE
Fatal error on Entry save

### ISSUE THREAD

**Issue by dsg-rob** [nystudio107/retour#33]
Hello,

I've installed Retour (1.0.15) but haven't configured anything in it yet. When I go to save an Entry, this error is shown:

`Fatal error: Using $this when not in object context in /var/www/html/craft/plugins/retour/RetourPlugin.php on line 88`

If I disable the plugin, everything works fine. This may be an issue with my setup but I did want to bring it up here just in case.

Thanks!

**Comment by khalwat** [comment]
That's very strange.  Can you give me details on your setup?  Craft version, php version, etc, etc.?

**Comment by dsg-rob** [comment]
Sure thing:

> Craft 2.6.2911
> PHP 5.3.3
> Apache Version 2.2.15 (Red Hat)

Is that enough info? Let me know if you need anything else.

**Comment by khalwat** [comment]
hmmmm.  Are you able to try this on a server that is running a more recent version of PHP?

**Comment by dsg-rob** [comment]
I've just installed it on a local server running PHP 5.5.29 and it's working fine. 

I also have Retour 1.0.15 running on a different site, using Craft 2.6.2911 and PHP 5.6.24 - that has been working as well.

It's looking like this might be a PHP 5.3.3 issue, huh.

**Comment by khalwat** [comment]
Yeah, confirmed it's a PHP 5.3 thing: http://stackoverflow.com/questions/27463584/php-using-this-when-not-in-object-context.

Unfortunately, I'm probably not going to fix this.

**Comment by dsg-rob** [comment]
No problem, thanks for looking into it! 👍
