### ISSUE TITLE
Old URL is redirecting to index.php?p=[path here]

### ISSUE THREAD

**Issue by wfendler** [nystudio107/retour#39]
I have the recommended htaccess from Craft, and it seems like all my 404s are making it to this line `RewriteRule (.+) index.php?p=$1 [QSA,L]` instead of the redirects in Retour.

**Comment by khalwat** [comment]
What is happening is what should happen. The request comes in and gets rewritten by Craft. Look at what the actual 404 URL is in Retour -> Statistics and set up a redirect for it

Also look at: https://craftcms.com/support/remove-index.php

**Comment by wfendler** [comment]
Perhaps I didn't write it clearly. I had redirects set up but even with them set up they were ending up as `index.php?p=some-path`

I think I just started to figure it out though. When importing from my `.htaccess` it was keeping the `(?i)` before it for case-insensitivity.

`RedirectMatch 301 (?i)/work/vote-no /new-path` was added to Retouer as a Regex Matched redirect with `(?i)/work/vote-no` but I'm now discovering that it looks like Retour treats all redirects set as "Regex Match" to be case-insensitive (doesn't need `(?i)`). Is that correct?

**Comment by khalwat** [comment]
yep, you're correct, it makes them all case-insensitive:

                case "regexmatch":
                    $matchRegEx = "`" . $redirect['redirectSrcUrlParsed'] . "`i";
                    if (preg_match($matchRegEx, $url) === 1)
                    {
