### ISSUE TITLE
Records with empty redirectSrcUrlParsed being created

### ISSUE THREAD

**Issue by timkelty** [nystudio107/retour#41]
I'm still seeing this issue with the latest version, so the check must need to be somewhere else as well.
https://github.com/nystudio107/retour/pull/35

Example:

```
{% if object.legacyId %}/buyersguide/accessories/showProduct.html.*prodID={legacyId}{% endif %}
```

Is resulting in an empty `redirectSrcUrlParsed`, and therefore all my 404s go to this entry.

I'm not quite sure how those rows are getting created, as I can't recreate it if I delete that row and re-save the entry...

**Comment by khalwat** [comment]
Any updates to this? I've been unable to reproduce

**Comment by timkelty** [comment]
No, ended up avoiding it by always having an `else` that was just the entry id.
So last I knew, it was still happening.

**Comment by khalwat** [comment]
If you re-save all of the entries for this channel, does this problem go away? Just do it by re-saving the section in question.
