### ISSUE TITLE
Substitution in destination URL?

### ISSUE THREAD

**Issue by marcusmoore** [nystudio107/retour#42]
Is it possible to provide support for regex substitutions in the destination url? In my case the incoming URLs are uppercase while the destination is lowercase. I tried to use `\L$1` without success.

Thanks!

**Comment by khalwat** [comment]
Currently there's no way to do that unfortunately.

**Comment by AMandujano-BI** [comment]
Any update on this?

**Comment by khalwat** [comment]
You're commenting on the old Craft 2.x plugin repo -- are you sure this is where you want to be, @AMandujano-BI ?

**Comment by AMandujano-BI** [comment]
oops, nope you are right, thanks! will go to the correct one
