### ISSUE TITLE
Craft addTrailingSlashesToUrls config setting is ignored for internal redirectDestUrl

### ISSUE THREAD

**Issue by kevinsmith** [nystudio107/retour#45]
The [addTrailingSlashesToUrls](https://craftcms.com/docs/config-settings#addTrailingSlashesToUrls) system config setting isn't taken into account when redirecting to local URLs. This is mostly an issue for dynamic entry redirects because the redirectDestUrl is automatically determined by Retour, which doesn't have a trailing slash by default.

What I expected: I have that config item set to `true`, and I expected Retour's dynamic entry redirects to redirect to a destination URL with a trailing slash.

What happened instead: Retour redirects to a destination URL without a trailing slash.

**Comment by zizther** [comment]
+1

**Comment by khalwat** [comment]
I pushed a fix for this to the `develop` branch:

https://github.com/nystudio107/retour/tree/develop

**Comment by kevinsmith** [comment]
It should be noted that the effect of this setting is saved to the database, so it permanently affects all dynamic entry redirects with whatever its setting was at the time the entry was saved.

This is perhaps not the intended behavior. If I'm changing that config setting, I would expect it to have a general, consistent effect on the entire system, not change the way a particular entry's redirect is saved to the database.

**Comment by khalwat** [comment]
Right, you'll need to re-save any Sections that have Retour Redirect FieldTypes added to them, which will cause them all to be updated with this new setting.
