### ISSUE TITLE
"Last Hit" datetime isn't adjusted to timezone set in General Settings

### ISSUE THREAD

**Issue by kevinsmith** [nystudio107/retour#47]
From what I can tell, the "Last Hit" times across the Retour interface are just showing the UTC time and not adjusting the datetime according to the system timezone as saved in General Settings, as one would expect.

**Comment by khalwat** [comment]
Yeah, it's giving you the data based on whatever the server timezone is set to.

**Comment by kevinsmith** [comment]
Understood, but I'm not sure I'd agree that this isn't a bug. Given that there is [a global setting](https://craftcms.com/docs/config-settings#timezone) to localize the time displayed in the UI, I would argue it's a reasonable expectation to assume it would affect the UI for plugins too.

I'm not saying you should drop everything and do it now. I certainly understand your time is limited! Just suggesting this make it onto a list of future fixes.
