### ISSUE TITLE
Undefined index notices on 404s

### ISSUE THREAD

**Issue by timkelty** [nystudio107/retour#50]
I had a PR I thought quickly fixed this...but it seems it broke something else, so I'm just posting this issue for now.

> ( ! ) Notice: Undefined index: redirectMatchType in /Users/timkelty/Sites/paddling/craft/plugins/retour/services/RetourService.php on line 176

> ( ! ) Notice: Undefined index: redirectMatchType in /Users/timkelty/Sites/paddling/craft/plugins/retour/services/RetourService.php on line 214

**Comment by khalwat** [comment]
Is it possible this is the logging code that's generating this error?

**Comment by timkelty** [comment]
Doesn't seem to be happening after the latest merges, so let's close.

**Comment by samhibberd** [comment]
Hi,

I am out of the office on annual leave, returning Monday 30th January. All emails will be dealt with on my return.

If you do have anything urgent please don’t hesitate to get in contact with Ben on 01962 809 103 or ben@fruitstudios.co.uk.

Thank you,

Sam Hibberd
 
Fruit Studios Ltd
First Floor
100 High Street
Winchester
SO23 9AH
 
====================================================

This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify Fruit Studios Ltd immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Fruit Studios Ltd does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. Opinions expressed in this email are those of Sam Hibberd, and do not necessarily reflect those of Fruit Studios Ltd. If verification is required please request a hard-copy version.

====================================================
