### ISSUE TITLE
Redirect on other trigger besides 404

### ISSUE THREAD

**Issue by ianshea** [nystudio107/retour#54]
This is a bit of a feature request. I've run into instances where someone wants/needs a redirect that replaces a current page on their site.

The entry however, may be used to define some kind of navigation element so the entry cannot be disabled/destroyed, and a redirect setup in Retour doesn't get triggered since the page doesn't 404.

I'm not sure if it's feasible ( or efficient ) to check and see if the page has an override specified via a custom field that would redirect it based on a Retour route regardless if it 404's or not, but this sure would be handy in a few instances.

We've worked around it by creating a dead template that does something like an `{% exit 404 %}` on load, but this seems pretty nasty. Thought I'd throw this here for discussion.

**Comment by khalwat** [comment]
The fundamental design that Retour works on is that it kicks in only after a 404 occurs.

If you have an existing template that is "catching" the page, you can just use the `{% redirect %}` tag in it, no?

https://craftcms.com/docs/templating/redirect

**Comment by ianshea** [comment]
True, it might be just me being a little lazy. 😀

 But here is a scenario:

- Have a channel of entries, only 1 type.
- It's decided that one or more of these items should redirect

To handle it with templating, we'd have to create a new type, add it to the section, point the existing entry to it. This involves a lift for us every time a fickle client needs a redirect. You could make it a little dynamic by creating a "redirect" type and handle it that way with field for a URL if we wanted to make it client controlled. But, then we're replicating that across sections, etc. which seems cumbersome and not very friendly.

I've seen clients request multiple redirects to the same place across different URLs for vanity things, and redirect older blog posts, etc. Which would make template handling it cumbersome to update in multiple places.

Original Page with Element:
`/original-page >>> //someotherurl.com`

URLs that don't really exist handled by Retour:
`/foo/bar/ >>> //someotherurl.com`
`/baz/foo/ >>> //someotherurl.com`

**Comment by khalwat** [comment]
I guess the part I'm not "getting" is why it's not throwing a 404 when you delete the thing that needs redirecting? Or are you saying that you keep the thing in place?

You mention that it "may be used to define some kind of navigation element so the entry cannot be disabled/destroyed," but shouldn't the navigation element be separate from the content?

**Comment by ianshea** [comment]
I'm saying that we're keeping the thing in place and not disabling/destroying it.

ie: It's an entry in a structure, and that structure is having a navigation derived from it.

Another example:

We had a client with a blog post up an entry discussing there soon to be released mobile app for an event. They trafficked the post through some email campaigns, and social channels. More relevant to this conversation, it was also listed in a carousel ( that pointed to the entry ), and displayed on their overall blog page.

When they released the app they wanted that blog entry to redirect to go download the app.

The conundrum comes in that if we have to disable/delete that entry to create a 404 to get the redirect to work. This then takes it out of the blog listing page, and also the carousels it was in as the entry is no longer alive in the system.

**Comment by khalwat** [comment]
IMO, that's a case where the client is trying to make "the thing" to two things at once. It's either a blog page, or it's not.

I would simply put a header on the blog that links to the actual app now that it's released.

The scheme you're discussing is likely going to be confusing to Google from a canonical POV, and also confusing to people.

In any event, whatever you decide to do, this isn't how Retour works. It doesn't intercept anything until a 404 has already happened.
