### ISSUE TITLE
404 error when clearing stats in Craft Admin

### ISSUE THREAD

**Issue by terryupton** [nystudio107/retour#55]
Nothing major, but noticed when clearing stats in the retour plugin it returns a 404 error page within craft admin panel. In my instance it is hitting this URL;
/cms/retour/clearStats/statistics/

**Comment by khalwat** [comment]
I'm not seeing this behavior. I just clicked on "Clear Stats" (the URL of which was https://nystudio107.com/admin/retour/clearStats ) and it took me to: https://nystudio107.com/admin/retour/statistics

Are you sure something else isn't amiss?

**Comment by terryupton** [comment]
Hmm odd. Ok I will test on another site and see if I see the same behaviour.
Not sure what else could cause this. Any ideas?

**Comment by khalwat** [comment]
I don't. I'll look at the code to see if anything makes sense, but it's at least not reproducible here 
(which really aids in finding and fixing issues)

**Comment by khalwat** [comment]
I'll close the ticket, but if you find any more information, please re-open it.
