### ISSUE TITLE
On save entry slug changes

### ISSUE THREAD

**Issue by MGxpwr** [nystudio107/retour#63]
When changes a slug of an entry we see it only works without a trailing slash. We think te code in z`RetourFieldType.php` 
```
if (craft()->config->get('addTrailingSlashesToUrls'))
        {
            $url = rtrim($url, '/') . '/';
        }
```

Doesnt get excuted when you save an entry. Is this true? If so is it possible to add this?

**Comment by khalwat** [comment]
I pushed a fix to `develop` that should take care of it for you:

https://github.com/nystudio107/retour/tree/develop

Let me know...
