### ISSUE TITLE
.htaccess import fails silently

### ISSUE THREAD

**Issue by aarmitage** [nystudio107/retour#64]
Hi there,

Thanks for your work on Retour - great little plugin for a migration we've just launched today.

We're having a problem importing our .htaccess file which seems to just fail silently. We've tried a few different combinations;

- .htaccess direct from the source. This includes redirects but also has some other rules included in it
- the same file, renamed to htaccess.txt. This time though we removed the additional rules

The rules are formatted like this:

`RewriteRule ^about-us$ /about-us/our-people [R=301,L]`
`RewriteRule ^our-mission$ /what-we-do/our-mission [R=301,L]`

We can't see any errors in the Craft logs, or our server logs. Are we doing something wrong, or could there be an issue with the plugin?

Any guidance would be much appreciated – thank you.

**Comment by khalwat** [comment]
So Retour actually ignores `RewriteRule` completely when importing `.htaccess` files:

https://github.com/nystudio107/retour/blob/master/controllers/RetourController.php#L22

As you can see from the code, I originally had it doing it, but the problem is that `RewriteRule` can be very tricky to actually parse correctly, and I thought it was better to not do it at all, rather than potentially do it wrong.

**Comment by khalwat** [comment]
If you want, you can uncomment that code block and try importing it again. Do check over the resulting import for accuracy, though.

**Comment by aarmitage** [comment]
Great - thank you. We've actually just reformatted the redirects and the import's worked using the `Redirect` rule.

Might be worth a quick note in the docs as it still references the `RewriteRule` as a match.

Cheers.

**Comment by khalwat** [comment]
I was just double-checking that to make sure :)

**Comment by khalwat** [comment]
https://github.com/nystudio107/retour/commit/996886a05cce16c0f7f4456890e05552f3847ee5

Thanks, sorry for the incorrect documention.

**Comment by aarmitage** [comment]
No problem - thanks for the quick reply :-)

**Comment by iainhenderson** [comment]
Would it be possible to merge this documentation fix into master? I can see it's fixed in develop, but the master readme still suggests RewriteRule's can be imported.
