### ISSUE TITLE
Retour only shows the first 100 static redirects in CP view

### ISSUE THREAD

**Issue by kevinsmith** [nystudio107/retour#65]
Note that by this I don't mean that it shows the first 100 redirects by default. I mean that it _only_ shows the first 100 redirects, even after I try to page through them all. The interface implies that it's loading all existing redirects, but it stops at 100.

I suspect this was done for performance reasons, which is understandable, but a better route to take would be to lazy load them in the interface.

As always, thank you for your work on this!

**Comment by khalwat** [comment]
You can configure this via the `config.php`:

https://github.com/nystudio107/retour/blob/master/config.php#L31

In general, though, if you have over 100 static redirects, it might be time to look and see if any can be consolidated via RegEx matching or via using the Retour FieldType.
