### ISSUE TITLE
Statistics Filter

### ISSUE THREAD

**Issue by kaspar-allenbach** [nystudio107/retour#66]
Is it possible to filter the statistics of retour?

The amount of Wordpress crawling is insane.

**Comment by khalwat** [comment]
You mean filter them so that they aren't recorded at all? Currently, no.

What I do is I set up a wildcard redirect to send all WordPress-probing to WordPress.org:

https://github.com/nystudio107/nginx-craft/blob/master/sites-available/somedomain.com.conf#L47
