### ISSUE TITLE
Run exact match checks before regex matches

### ISSUE THREAD

**Issue by 3noch** [nystudio107/retour#70]
When you have many redirects, your regexs and exact matches can start to overlap. Which ones are tried first seems to be undefined. At the very least I think it makes sense that exact matches would always precede regex matches.

**Comment by khalwat** [comment]
Definitely agree that this is a desired improvement.

**Comment by 3noch** [comment]
This was actually fixed in https://github.com/nystudio107/retour/commit/fdc897755c2dce153e439b4b69fc6b41817bd28f

**Comment by jerwarren** [comment]
I have 1.0.22 and it definitely didn't behave this way until I changed the sorting, though now that I look at the values for redirectMatchType it should.  I just put it back to ascending and it's is 100% using regexmatch before using exactmatch.  Flipped it back to descending and it's using exactmatch first

**Comment by jerwarren** [comment]
I'm wrong, but I don't understand how. Caching must have been thwarting me
