### ISSUE TITLE
Can't redirect to homepage

### ISSUE THREAD

**Issue by evanwarner** [nystudio107/retour#72]
When setting up a **RegEx Match** redirect, there doesn't seem to be anything I can put in the **Destination URL** field in order to redirect to my site's homepage. With **Exact Match** rules, `/` works, but with RegEx set, it seems to prepend `/` to the field value, giving me issues.

I've tried:

Leaving the field empty: The rule disappears when saved (it's removed altogether from `retour_static_redirects` table).

`/`: Results in a non-action. The log reports `Redirecting to //` which equates to an empty protocol-relative URL.

` ` (a space): This works _unless_ the legacy URL has a querystring, in which case it redirects to `/%20?query=string`, giving me a 404 on the result. So basically this works because browsers just ignore the trailing whitespace in the URL.

`http://example.dev`: Trying an absolute URL just appends it like it was relative, redirecting to `http://example.dev/http://example.dev`.

**Comment by khalwat** [comment]
Just to clarify, is this using the FieldType, or is this using Static Redirects?

I set up a simple test using a Static Redirect, and it seems to work okay:

<img width="446" alt="screen shot 2017-08-30 at 9 15 28 am" src="https://user-images.githubusercontent.com/7570798/29874143-e21f4976-8d63-11e7-8f73-472223019485.png">

**Comment by khalwat** [comment]
I looked over the code, and I don't see anywhere that it's explicitly adding a `/` -- so perhaps you have a capture group in your regex that's errantly capturing a `/` in the original URL?

**Comment by evanwarner** [comment]
It did start working, but it was inconsistent for a while. Seems to be performing fine now. Unsure what was wrong before.
