### ISSUE TITLE
Discard querystring option

### ISSUE THREAD

**Issue by evanwarner** [nystudio107/retour#73]
By default, querystrings on the legacy URL are appended to the destination URL. It would be nice to have a default setting and per-rule override whether or not to do this. As of now, I have to make everything a RegEx rule and use `(\?.*)?` on the end to discard the querystring.

**Comment by khalwat** [comment]
Well, it doesn't really do anything by default, it just passes in the source URL, and lets your RegEx do whatever it wants to it. However in the build in `develop` I added:

* Added a `alwaysStripQueryString` setting to `config.php` (defaults to `false`)

https://github.com/nystudio107/retour/tree/develop
