### ISSUE TITLE
Increase character limit on craft_retour_stats column

### ISSUE THREAD

**Issue by supercooljames** [nystudio107/retour#74]
Just got an error where a referrer URL was more than 255 chars 😩

Excellent, excellent plugin btw

**Comment by erikverheij** [comment]
I'm experiencing the same problem. In my opinion the reffererUrl should always be truncated to make sure it doesn't go over the column max length. You have no control over what query params are being appended to the url. Therefore you can't set a reliable limit.

In my case traffic from some Adwords campaigns (with a lot of query params) landed on a page that resulted in this error :(.

**Comment by khalwat** [comment]
This is fixed in the build in `develop`:

https://github.com/nystudio107/retour/tree/develop

Thanks to @erikverheij for the PR!
