### ISSUE TITLE
Regex replace

### ISSUE THREAD

**Issue by billythekid** [nystudio107/retour#77]
Is there any way to conduct a regex replacement in the redirect to field? For example if I want to swap out non-matching underscores in a 'slug' to hyphens? Can the twig/craft replace filter be used?

**Comment by khalwat** [comment]
hmmmm unfortunately, no, it doesn't evaluate it as a Twig micro-template, only as a regular expression. You should be able to make a regex that does this replacement for you, though.

http://regexr.com/ is a great place to test such things.
