### ISSUE TITLE
Saving an entry causes mutiple retour redirect fields to have the same values

### ISSUE THREAD

**Issue by epcliff** [nystudio107/retour#80]
Hi. My team has been using Retour plugin. It says on the documentation that we can add as many Retour Redirect fields as we want in an entry type. We've added two Retour Redirect fields and whenever we update an entry, the values on those fields end up the same. They have different field names so I'm just wondering if you guys have this issue before and know what causes to do this.

**Comment by khalwat** [comment]
hmmm, yeah this sounds like a bug with multiple Retour fields in a single entry type.

**Comment by sarahtooley** [comment]
We are experiencing the bug on non-Single entries as well.

**Comment by khalwat** [comment]
hmmmm, yeah it looks like the documentation is wrong, because what it's doing is it's keying off of the entry's `elementId`, which will be the same for all Redirect fields.

I will update the documentation.

**Comment by rungta** [comment]
We encountered this bug on a project as well. Does this mean that Retour cannot/will not support multiple Redirect fields on a single entry?

**Comment by sarahtooley** [comment]
@rungta We found a way around the issue. If you go to the Retour tab and save a static redirect, you are able to add multiple redirects for one path. They just have to be made as _separate_ static redirects.

**Comment by rungta** [comment]
@sarahtooley Sure, that is what we resorted to for now. However the benefit of the Redirect field was the ability to declare a dynamic redirect, and not hardcoding the target destination, both of which are very useful.
