### ISSUE TITLE
Plugin causing HTTP ERROR 500 on save within Craft

### ISSUE THREAD

**Issue by sarah3585** [nystudio107/retour#81]
I'm getting a 'HTTP ERROR 500' on save of any Craft entry when this plugin is enabled.
Any other information I can provide you with let me know.

**Comment by khalwat** [comment]
@sarah3585 , that's almost certainly due to some kind of server misconfiguration.

If you can give me the full stack trace from the error, I'll attempt to help you sort it out though.

**Comment by sarah3585** [comment]
Thanks, appreciate it. It's hosted on Windows (not my choice!)

From craft.log:
`2017/08/26 01:20:46 [error] [exception.Craft\HttpException.404] exception 'Craft\HttpException' in E:\HostingSpaces\gbcc\gbcc.org.uk\craft\app\controllers\TemplatesController.php:72
Stack trace:
#0 [internal function]: Craft\TemplatesController->actionRender('plus/mytag_j.ph...', Array)
#1 E:\HostingSpaces\gbcc\gbcc.org.uk\craft\app\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(Craft\TemplatesController), Array)
#2 E:\HostingSpaces\gbcc\gbcc.org.uk\craft\app\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(Craft\TemplatesController), Object(ReflectionMethod), Array)
#3 E:\HostingSpaces\gbcc\gbcc.org.uk\craft\app\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 E:\HostingSpaces\gbcc\gbcc.org.uk\craft\app\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 E:\HostingSpaces\gbcc\gbcc.org.uk\craft\app\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 E:\HostingSpaces\gbcc\gbcc.org.uk\craft\app\framework\web\CWebApplication.php(282): CController->run('render')
#7 E:\HostingSpaces\gbcc\gbcc.org.uk\craft\app\framework\web\CWebApplication.php(141): CWebApplication->runController('templates/rende...')
#8 E:\HostingSpaces\gbcc\gbcc.org.uk\craft\app\etc\web\WebApp.php(290): CWebApplication->processRequest()
#9 E:\HostingSpaces\gbcc\gbcc.org.uk\craft\app\framework\base\CApplication.php(185): Craft\WebApp->processRequest()
#10 E:\HostingSpaces\gbcc\gbcc.org.uk\craft\app\index.php(62): CApplication->run()
#11 E:\HostingSpaces\gbcc\gbcc.org.uk\wwwroot\index.php(20): require_once('E:\HostingSpace...')
#12 {main}
REQUEST_URI=/plus/mytag_j.php?aid=6022
HTTP_REFERER=http://www.gbcc.org.uk/1.php
---`
