### ISSUE TITLE
Redirect rule active but not in the list

### ISSUE THREAD

**Issue by martinomancino** [nystudio107/retour#83]
Hi,
I have kind of 100 redirects because a site migration.
I just created another test redirect and it works as expected but I can't remove it because it's not in the list. Tried searching by name, going through the list but nothing not there.
also I tried to re-create it and the plugin tells me can't be crated I think because that rule is already in place.

Can you tell me how I can get rid of that rule now?
Thanks

**Comment by khalwat** [comment]
It's actually in the list, there is just a display limit; you can change this via the `config.php` settings.
