### ISSUE TITLE
Unable to see recently added static redirects.

### ISSUE THREAD

**Issue by sarahtooley** [nystudio107/retour#87]
Our process:
1. Login to Craft and access Retour.
2. Create a new Static Redirect.
3. Upon confirming save, look for the redirect in the search list. 

Result: The redirect is not found, but seems to be working properly when we test the redirect.

**Comment by khalwat** [comment]
Is it possible that you have more than 100 redirects? It sorts the redirects by most recent hit, and if you have that many redirect, it might not be displayed.

You can increase the display limit via the `config.php` file:

https://github.com/nystudio107/retour/blob/master/config.php#L33

**Comment by sarahtooley** [comment]
Sweet! That's exactly it. Thanks!
