### ISSUE TITLE
creating static redirects based on url parameters

### ISSUE THREAD

**Issue by rolfkokkeler** [nystudio107/retour#88]
I have page visits with paths like:
`http://eu.aoc.com/en/products?showUid=10&useCacheHash=1`

These seem to originate from Typo3 systems, I do not want these visits.
I'm trying to deny access to the site using the following Legacy URL pattern:
`(.*)showUid(.*)`
with regex match with redirect to homepage status 410.

This however does not redirect.

**Comment by khalwat** [comment]
Verify that your RegEx matches as expected; as long as visiting the URL throws a 404, and the RegEx matches, Retour will handle it.

Can be helpful: https://regexr.com/
