### ISSUE TITLE
Enhancement: Bulk add/import

### ISSUE THREAD

**Issue by michaelroper** [nystudio107/retour#9]
Would be great to have a way to add a bulk lot of URLs + redirects at once, either by pasting CSV format text into a textarea, or by importing a CSV file with specified columns (to match the db table columns i guess).

**Comment by jamesmacwhite** [comment]
This would be a nice feature. I recently had to do a bulk import of redirects with Retour, the way I had to do it was loop through a text file with the old and new URL paths (separated by a space per line) which then outputted the redirects data into an SQL row that matched the Craft schema for use in an `INSERT` query for the `craft_retour_static_redirects` table. 

Not exactly clean, bulk import via CSV welcome to save others the hassle!

**Comment by khalwat** [comment]
Implemented the ability to import from `.htaccess` files in version 1.0.15:

https://github.com/nystudio107/retour

I will leave this open since it leaves people using Nginx or redirects from some other source out in the cold.

**Comment by khalwat** [comment]
Seems easy enough to get redirects into an `.htaccess` format for importing, so I'll close it out.

**Comment by Emkaytoo** [comment]
FWIW, adding csv import support would allow for an easier team-based workflow where we have a content manager/SEO manage that, without having to write it in htaccess format first.

**Comment by tekstrand** [comment]
CSV import for new redirects as well as an export that can then be reimported to update existing redirects would be very helpful for content editors.

**Comment by khalwat** [comment]
This is something that the Craft 3 version has @tekstrand https://github.com/nystudio107/craft-retour
