### ISSUE TITLE
Basic redirect not working

### ISSUE THREAD

**Issue by frankharrison-wj** [nystudio107/retour#94]
I'm trying to add a very basic redirect but it's not working. It's as simple as this:

Legacy URL Pattern: /sustainable-energy/news-and-opinion
Destination URL: /about/news-and-opinion
Pattern Match Type: Exact Match
Redirect Type: 301

But when I go to mysite.com/sustainable-energy/news-and-opinion it doesn't redirect. Other similar redirects set up in Retour work as expected (they are all Exact Match) and there's nothing non-standard in my .htaccess.

Any ideas how to diagnose this issue? I'm on Retour 1.0.19, Craft 2.6.2964.

Thanks!

**Comment by mierla** [comment]
I'm having this problem too - did you ever get it figured out?

**Comment by frankharrison-wj** [comment]
Hmm, that's odd that they would work after some time had passed. I never figured mine out – ended up using .htaccess for that redirect.

**Comment by brandondeweese** [comment]
Anyone have an answer for this? Ive used this plugin in the past and if seemed to work great... I can't get it to redirect a simple blog entry back to the blog page.

**Comment by Strikwerda** [comment]
Hi there. I'm having a similar issue. I work for an SEO company and just took over a client that is using Craft CMS and Retour. Entering in some basic static redirects, Exact Match, 301 - Permanents. Checking back half-an-hour later and not working.  Any areas to troubleshoot?

**Comment by Strikwerda** [comment]
Anyone check this support thread?

**Comment by brandondeweese** [comment]
I've switched to this plugin until there's a fix.

https://github.com/davist11/craft-reroute

**Comment by frankharrison-wj** [comment]
Shame that Cradt Reroute doesn't do regex – means I'd need two separate plugins for different types of redirects. Hope this gets fixed in Retour soon!

**Comment by jerwarren** [comment]
I was just trying to get this to work and eventually noticed that Retour only applies to urls that return a 404.  So if you're trying to redirect a url that currently exists like I am, it won't work.

**Comment by frankharrison-wj** [comment]
Hmm, that could have been the issue in my case – to be honest I can't remember whether the old URL was returning a 404 or not! Thanks for posting though.

**Comment by khalwat** [comment]
Yes, Retour ONLY works once a 404 has already been thrown, as stated in the docs. The reason it works that way is for performance reasons; other plugins can slow down _every_ request.

@Strikwerda I'm using the plugin on a number of very high traffic sites, and the redirects are most definitely working.

Either the URL you're trying to redirect is _not_ throwing a 404, or the RegEx / url you're trying to redirect from is incorrect.
