### ISSUE TITLE
Mass warnings in Craft's phperrors.log file

### ISSUE THREAD

**Issue by ncc-jwood** [nystudio107/retour#97]
This plugin is kicking up a ton of warnings in Craft's phperrors.log file

`PHP Warning:  preg_match(): Compilation failed: nothing to repeat at offset 0 in /home/forge/ncc-ccn.gc.ca/craft/plugins/retour/services/RetourService.php on line 217`

Getting one of these every few seconds, so it seems it's being kicked up every time the plugin is called.

**Comment by khalwat** [comment]
Sounds like it might be an issue with a RegEx that you have set?

https://stackoverflow.com/questions/17346591/preg-match-with-php-compilation-failed
