### ISSUE TITLE
Redirects only shows 100 entries in Admin Panel

### ISSUE THREAD

**Issue by terryupton** [nystudio107/retour#99]
A bug I believe but the Redirects section in the Craft Admin panel only shows 100 entries. I currently have 107 redirects but the results only shows 100 and now way to paginate past 5 pages of results.
Let me know if you need any more info or a DB dump.

**Comment by scottwakefield** [comment]
@terryupton, the 100 redirects limit is set in the plugin configuration file. If you create a `retour.php` config file in your project's `craft/config/` directory and add:

```
<?php

return array(

    /**
     * How many static redirects to display in the Admin CP
     */
    "staticRedirectDisplayLimit"  => null,

    /**
     * How many dynamic redirects to display in the Admin CP
     */
    "dynamicRedirectDisplayLimit" => null,

);
```

that should disable the limit and show all redirects. You can see all configuration options here: https://github.com/nystudio107/retour/blob/master/config.php

Hope that helps!

**Comment by terryupton** [comment]
Perfect thanks @scottwakefield.
